name: ⚙️ End-to-end Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
jobs:
  e2e:
    name: ⚙️ End-to-end test
    if:
      # ignore all-contributors PRs
      ${{ github.repository == 'zainfathoni/senar.ai' &&
      !contains(github.head_ref, 'all-contributors') }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: 🐑 Clone repository
        uses: actions/checkout@v3

      - name: 🦀 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ⛓ Install Node deps
        uses: bahmutov/npm-install@v1

      - name: 🌐 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: ▶️ Run end-to-end tests
        run: npm run test:e2e

      - name: ⬆️ Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
